import type { Metadata } from "next";
import "./globals.css";
import styles from '../styles/Body.module.scss'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { toastConfig } from '../utils/toastConfig'
import ClientWrapper from '../components/ClientWrapper'
import Auth from '../components/Auth'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fa" dir="rtl">
      <body className={styles.body} cz-shortcut-listen="true">
        <ClientWrapper>
          <Auth>
            {children}
          </Auth>
        </ClientWrapper>
        <ToastContainer {...toastConfig} newestOnTop={false} pauseOnFocusLoss />
      </body>
    </html>
  );
}
